services:
  - type: web
    name: ecommerce-sga
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn Ecommerce_sga.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: Ecommerce_sga.settings
      - key: PYTHON_VERSION
        value: 3.10
