services:
  - type: web
    name: ecommerce
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn Ecommerce_sga.wsgi"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: seu_projeto.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
