# Generated by Django 5.2 on 2025-04-07 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sga', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20)),
                ('chave', models.CharField(max_length=44)),
                ('cliente', models.CharField(max_length=100)),
                ('data', models.DateField()),
                ('produto', models.CharField(max_length=100)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('autorizada', 'Autorizada'), ('rejeitada', 'Rejeitada'), ('cancelada', 'Cancelada'), ('denegada', 'Denegada'), ('inutilizada', 'Inutilizada')], max_length=20)),
            ],
        ),
    ]
