# Generated by Django 5.2 on 2025-04-08 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sga', '0003_produto_altura_produto_ativo_produto_categoria_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marketplace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=False)),
                ('token', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VendaMarketplace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto', models.CharField(max_length=200)),
                ('data_venda', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('marketplace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sga.marketplace')),
            ],
        ),
    ]
